"""Cloud training services package."""

from .async_job_store import AsyncJobStore
from .base import (
    CloudJobInfo,
    CloudJobStatus,
    CloudTrainerService,
    CloudUploadBackend,
    DashboardMetrics,
    JobType,
    UnifiedJob,
)
from .cloud_upload_service import CloudUploadService, ReplicateUploadBackend
from .commands import (
    CancelJobCommand,
    Command,
    CommandContext,
    CommandDispatcher,
    CommandResult,
    CommandStatus,
    DeleteJobCommand,
    SubmitJobCommand,
    SyncJobsCommand,
    get_dispatcher,
)
from .container import (
    ServiceContainer,
    container,
    get_job_store,
    get_queue_manager,
    get_quota_checker,
    get_secrets_manager,
    get_user_store,
    reset_container,
    set_job_store,
    set_secrets_manager,
    set_user_store,
)
from .exceptions import (
    AuthenticationError,
    AuthorizationError,
    CloudError,
    ConfigNotFoundError,
    ConflictError,
    CostLimitExceededError,
    DatabaseError,
    DuplicateError,
    InternalError,
    InvalidConfigError,
    InvalidInputError,
    InvalidPayloadError,
    InvalidSignatureError,
    InvalidTokenError,
    IPNotAllowedError,
    JobLimitExceededError,
    JobNotFoundError,
    JobStateError,
    MissingTokenError,
    NotFoundError,
    NotReadyError,
    PermissionDeniedError,
    ProviderAPIError,
    ProviderError,
    ProviderTimeoutError,
    ProviderUnavailableError,
    QuotaExceededError,
    RateLimitError,
    ServiceUnavailableError,
    UserNotFoundError,
    ValidationError,
    register_exception_handlers,
    to_http_exception,
)
from .job_logs import fetch_job_logs, get_inline_progress, parse_training_stage
from .job_submission import JobSubmissionService, SubmissionContext, SubmissionResult
from .job_sync import sync_active_job_statuses, sync_replicate_jobs
from .metrics_service import MetricsService
from .protocols import (
    EventEmitterProtocol,
    JobStoreProtocol,
    MetricsServiceProtocol,
    ProviderClientProtocol,
    QueueStoreProtocol,
    SecretsProviderProtocol,
    UploadServiceProtocol,
    UserStoreProtocol,
)
from .replicate_client import ReplicateCogClient
from .secrets import (
    AWSSecretsManagerProvider,
    EnvironmentSecretProvider,
    FileSecretProvider,
    HashiCorpVaultProvider,
    SecretProvider,
    SecretsManager,
    get_secrets_manager,
)

__all__ = [
    # Base types
    "AsyncJobStore",
    "CloudJobInfo",
    "CloudJobStatus",
    "CloudTrainerService",
    "CloudUploadBackend",
    "CloudUploadService",
    "DashboardMetrics",
    "JobType",
    "MetricsService",
    "ReplicateCogClient",
    "ReplicateUploadBackend",
    "UnifiedJob",
    # Job services
    "JobSubmissionService",
    "SubmissionContext",
    "SubmissionResult",
    "fetch_job_logs",
    "get_inline_progress",
    "parse_training_stage",
    "sync_active_job_statuses",
    "sync_replicate_jobs",
    # Commands
    "CancelJobCommand",
    "Command",
    "CommandContext",
    "CommandDispatcher",
    "CommandResult",
    "CommandStatus",
    "DeleteJobCommand",
    "SubmitJobCommand",
    "SyncJobsCommand",
    "get_dispatcher",
    # Protocols
    "EventEmitterProtocol",
    "JobStoreProtocol",
    "MetricsServiceProtocol",
    "ProviderClientProtocol",
    "QueueStoreProtocol",
    "SecretsProviderProtocol",
    "UploadServiceProtocol",
    "UserStoreProtocol",
    # Secrets
    "AWSSecretsManagerProvider",
    "EnvironmentSecretProvider",
    "FileSecretProvider",
    "HashiCorpVaultProvider",
    "SecretProvider",
    "SecretsManager",
    "get_secrets_manager",
    # Exceptions
    "AuthenticationError",
    "AuthorizationError",
    "CloudError",
    "ConfigNotFoundError",
    "ConflictError",
    "CostLimitExceededError",
    "DatabaseError",
    "DuplicateError",
    "InternalError",
    "InvalidConfigError",
    "InvalidInputError",
    "InvalidPayloadError",
    "InvalidSignatureError",
    "InvalidTokenError",
    "IPNotAllowedError",
    "JobLimitExceededError",
    "JobNotFoundError",
    "JobStateError",
    "MissingTokenError",
    "NotFoundError",
    "NotReadyError",
    "PermissionDeniedError",
    "ProviderAPIError",
    "ProviderError",
    "ProviderTimeoutError",
    "ProviderUnavailableError",
    "QuotaExceededError",
    "RateLimitError",
    "ServiceUnavailableError",
    "UserNotFoundError",
    "ValidationError",
    "register_exception_handlers",
    "to_http_exception",
    # DI Container
    "ServiceContainer",
    "container",
    "get_job_store",
    "get_queue_manager",
    "get_quota_checker",
    "get_secrets_manager",
    "get_user_store",
    "reset_container",
    "set_job_store",
    "set_secrets_manager",
    "set_user_store",
]
