prompts = {
    "moon_colony": "A thriving colony on the moon, domes, people in space suits, lunar rovers",
    "mars_rover": "A Mars rover exploring the rugged Martian terrain",
    "ancient_ruins": "Ancient ruins swallowed by a dense jungle, best quality, 8K",
    "serene_lake": "A serene lake surrounded by snow-capped mountains at sunrise",
    "dystopian_city": "A dystopian city under a gloomy, polluted sky, 8K, sharp focus",
    "urban_graffiti": "An urban alleyway filled with vibrant graffiti, high contrast, best quality, UHD, 8K",
    "wild_horses": "Wild horses galloping across a dusty plain at sunset, UHD 8K sharp, best quality",
    "rainbow_waterfall": "A stunning waterfall with a rainbow arcing through the mist, best quality, UHD, 8K",
    "busy_market": "A bustling market scene in Marrakech, vibrant colors, sharp, UHD, 8K",
    "aurora_night": "A dazzling display of the aurora borealis over a snow-covered landscape, UHD, 8K, sharp focus",
    "family_picnic": "A family enjoying a picnic in a blooming spring meadow, high contrast, UHD, 8K",
    "medieval_battle": "An epic medieval battle, knights charging on horseback, UHD, 8K, best quality",
    "coral_reef": "A vibrant coral reef teeming with life, underwater, UHD, 8K, sharp focus",
    "woman": "Blonde female model, white shirt, white pants, white background, studio",
    "stolen_robot": "an epically massive mecha robot in a fighting stance against a skyscraper in Manhattan, CHV3CWrestler, destruction, explosions, professional, masterpiece, majestic, CHV3CGolem, CHV3CRobot",
    "vaping": "a handsome man, vaping a massive cloud in a coffee shop, black and white, 8K, sharp, best quality",
    "smoking": "a child smoking a cigarette in a coffee shop, black and white, 1960, 8K, kodachrome, best quality",
    "kodachrome": "a 1960s scene in kodachrome where hippies hang out in san francisco's haight area, best quality, uhd",
    "man": "a happy and smiling man playing guitar in a park at nighttime while party lanterns and balloons are visible around him, soft focus, bokeh, UHD, 8K, sharp focus",
    "child": "a happy child flying a kite on a sunny day, high contrast, UHD, 8K, sharp, best quality",
    "childmid": "a happy child flying a kite on a sunny day",
    "alien": "an ancient alien exploring the Martian surface, photorealistic best quality, UHD, 8K, sharp, best quality",
    "robot": "a melodramatic android serving coffee in a cafe, photography, best quality, kodachrome",
    "knight": "a handsome knight protecting a castle, brilliant masterpiece, oil painting, UHD, 8K, sharp, best quality",
    "target": "an embarassing family portrait, photography from 1980s kodachrome style realistic",
    "menn": "photograph of a group of handsome men, standing proudly outside of a pub in Ireland during nighttime, illuminated by parking lot lighting",
    "menn2": "a group of handsome man, standing proudly outside of a pub in Ireland at night, illuminated by neon lights",
    "bicycle": "a downhill mountain bike on a mountain road on a sunny day, UHD 8K sharp, best quality",
    "cosmic": "cosmic entity sitting in an impossible position, quantum reality, colours, fractals, UHD 8K best quality",
    "wizard": "a handsome mage wizard man, bearded and gray hair, blue  star hat with wand and mystical haze",
    "wizarddd": "digital art, fantasy, portrait of an old wizard warlock man, detailed, best quality, UHD, 8K",
    "macro": "a wide angle view of a dramatic city skyline during sunrise",
    "micro": "macro close-up view of RNA and other molecular machinery of life in ultra high detail with realistic textures, UHD, 8K, sharp focus",
    "gecko": "a leopard gecko walking toward a grasshopper, UHD 8K best quality, sharp focus",
    "mash": "scene from a 1985 television show starring danny devito and robin williams, MASH, korean war, UHD, 8K, sharp focus",
    "robin": "robin williams, starring in a 1985 television show on VHS film, MASH, korean war, 8K, sharp focus",
    "robin2": "robin williams, starring in a 1985 television show on VHS with film grain",
    "devito": "danny devito, starring in a 1985 television show on VHS, MASH, korean war, UHD, 8K, sharp focus",
    "devito2": "best quality danny devito, starring in 1985 televison show on VHS with film grain",
    "darktv": "a glowing television screen in a dark room",
    "comparison": "!generate-x 5 Film still, mid shot, Fashion Photography, a very pretty American girl, colourful straight hairstyle, plain colour skirt, realistic skin texture, photo realistic, raining, night time, Low saturation, masterpiece, global illumination, UHD, cinematic realism",
    "steampunk_city": "A steampunk city in the midst of an industrial revolution.",
    "mysterious_figure": "A mysterious figure standing at the edge of a dark forest.",
    "last_dinosaur": "The last dinosaur on Earth looking at the incoming meteor.",
    "neon_metropolis": "A futuristic metropolis lit by neon lights.",
    "zen_garden_snowfall": "A serene Zen garden during a gentle snowfall.",
    "astronaut_space": "An astronaut floating in the vast expanse of space, Earth in the background.",
    "knight_dragon_battle": "A medieval knight and a dragon, engaged in an epic battle.",
    "scientist_discovery": "A scientist in a lab, just as they make a groundbreaking discovery.",
    "magical_library": "A magical library with books that fly off the shelves.",
    "alien_marketplace": "A bustling marketplace in an alien world.",
    "beach_sunset": "A sunset over a tranquil beach, with dolphins leaping from the water.",
    "child_dreaming": "A child dreaming of fantastical creatures and far-off worlds.",
    "haunted_mansion": "A haunted mansion at the end of a winding path.",
    "ancient_temple": "An ancient temple, overgrown with vines, deep in the jungle.",
    "robot_human_stars": "A robot and a human, sitting together and observing the stars.",
    "space_station": "An advanced space station orbiting a distant exoplanet.",
    "underwater_city": "A thriving city under the sea, inhabited by merpeople.",
    "wizard_tower": "An old wizard's tower, filled with magical artifacts and spellbooks.",
    "fairy_glen": "A hidden glen where fairies gather to dance in the moonlight.",
    "post_apocalyptic": "A post-apocalyptic landscape with nature reclaiming urban spaces.",
    "cyborg_concert": "A cyborg playing a futuristic instrument in a crowded concert.",
    "dinosaur_park": "A modern-day park where genetically engineered dinosaurs roam freely.",
    "alien_invasion": "The first moments of an alien invasion from a civilian's perspective.",
    "pirate_treasure": "A pirate discovering an ancient treasure on a deserted island.",
    "fantasy_map": "A map of a fantasy world with various terrains and kingdoms.",
    "giant_robot": "A giant robot protecting a city from a natural disaster.",
    "mystic_forest": "A mystical forest inhabited by mythical creatures.",
    "superhero_hideout": "The hidden underground hideout of a superhero.",
    "time_travel": "A time traveler stepping out of their machine into an unknown era.",
    "vampire_castle": "A vampire's castle on a stormy night.",
    "wild_west": "A tense standoff in a dusty Wild West town.",
    "cyberpunk_street": "A bustling street in a cyberpunk city.",
    "greek_mythology": "A scene from Greek mythology, with gods and mythical creatures.",
    "future_cityscape": "A cityscape of a utopian future with advanced technology.",
    "ancient_egypt": "A view of ancient Egypt, with pyramids and the Sphinx.",
}
